[versions]
android-gradle = "9.3.1"
kotlin-gradle = "2.4.10"
kotlinx-serialization = "1.11.0"
ktlint = "1.8.0"
maven-publish = "0.37.0"
spotless = "8.10.0"
tapmoc = "0.4.2"
okhttp = "5.5.0"
jsoup = "1.23.1"

[libraries]
injekt = { module = "com.github.mihonapp:injekt", version = "91edab2317" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

ktlint-cli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-gradle" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
tapmoc = { id = "com.gradleup.tapmoc", version.ref = "tapmoc" }
